# Generated by Django 5.0.6 on 2024-05-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("board_id", models.CharField(max_length=15, unique=True)),
                ("title", models.CharField(max_length=30)),
                ("content", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
